# Generated by Django 4.1.5 on 2023-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_form_address_checkout_form_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_form',
            name='dostavka',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
