# Generated by Django 4.1.5 on 2023-01-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
