# Generated by Django 4.1.5 on 2023-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='checkbox',
            new_name='back',
        ),
        migrations.AddField(
            model_name='products',
            name='front',
            field=models.BooleanField(default=False),
        ),
    ]
