# Generated by Django 4.1.5 on 2023-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_checkbox_products_back_products_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='frontimage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='back',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categoryphoto'),
        ),
        migrations.AddField(
            model_name='products',
            name='backimage',
            field=models.ImageField(null=True, upload_to='cards1'),
        ),
    ]
