# Generated by Django 4.1.5 on 2023-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_backimage_remove_products_front_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='orders',
            name='colorimg',
            field=models.ImageField(null=True, upload_to='colors'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pricedesign',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
