# Generated by Django 4.1.5 on 2023-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_color_orders_colorimg_orders_pricedesign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='borderimg')),
                ('price', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='colors')),
                ('price', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='colorimg',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pricedesign',
        ),
    ]
