# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_border_color_remove_orders_colorimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
