# Generated by Django 4.1.5 on 2023-01-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('front_img', models.ImageField(null=True, upload_to='variantsimg')),
                ('back_img', models.ImageField(null=True, upload_to='frontimgv')),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='BigChip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='back_image',
            field=models.ImageField(null=True, upload_to='backimgproducts'),
        ),
        migrations.AddField(
            model_name='products',
            name='front_image',
            field=models.ImageField(null=True, upload_to='frontimageproducts'),
        ),
        migrations.AddField(
            model_name='products',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='variants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
