# Generated by Django 4.1.5 on 2023-01-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_variants_delete_testimonials_remove_products_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
    ]
