# Generated by Django 4.1.5 on 2023-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
