# Generated by Django 4.1.5 on 2023-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_title_products_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(default=0),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
