# Generated by Django 4.1.5 on 2023-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_products_price_products_url_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
    ]
