# Generated by Django 4.1.5 on 2023-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_products_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
